name: Check Winget Package Availability

on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow daily
  push:
    branches: []

jobs:
  check_packages:
    runs-on: windows-latest

    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Python script
        working-directory: ./tools
        run: |
          python check_packages.py

